[package]
name = "trails-api-extraction"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
serde_json = "1.0"
reqwest = "0.12.23"
serde = { version = "1.0.219", features = ["derive"] }
log = "0.4.27"
simplelog = "0.12.2"
